---

name: Master CI/CD

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  master_ci_cd:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout del repositorio
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Configurar Python
      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.10.x

      # 3. Instalar dependencias
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Configurar variables de entorno
      - name: Setup environment variables
        run: |
          echo "DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }}" >> .env
          echo "DJANGO_DEBUG=${{ secrets.DJANGO_DEBUG }}" >> .env
          echo "DJANGO_ALLOWED_HOSTS=${{ secrets.DJANGO_ALLOWED_HOSTS }}" >> .env
          echo "POSTGRES_DATABASE=${{ secrets.POSTGRES_DATABASE }}" >> .env
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}" >> .env
          echo "POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}" >> .env
          echo "POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}" >> .env

      # 5. Construir la imagen Docker
      - name: Build Docker image (SHA)
        run: |
          docker build -t ${{ secrets.DOCKER_USER }}/${{secrets.DOCKER_REPOSITORY}}:${{ github.sha }} .

      # 6. Autenticarse en DockerHub
      - name: Docker Login
        env:
          DOCKER_USER: ${{ secrets.DOCKER_USER }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

      # 7. Subir la imagen Docker
      - name: Push Docker image (SHA)
        run: |
          docker push ${{ secrets.DOCKER_USER }}/${{secrets.DOCKER_REPOSITORY}}:${{ github.sha }}
